defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

development:
  <<: *defaults
  database: eventcal_development

test:
  <<: *defaults
  database: eventcal_test

production:
  <<: *defaults
  database: eventcal_production
